//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrashLab.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrashLab.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a number of objects that will block the fReachable queue..
        /// </summary>
        internal static string FinalizerBlock_Help {
            get {
                return ResourceManager.GetString("FinalizerBlock_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go into the light.  Don&apos;t be afraid of the light..
        /// </summary>
        internal static string FinalizerBlock_Hint {
            get {
                return ResourceManager.GetString("FinalizerBlock_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 4 Finalizer: Blocked.
        /// </summary>
        internal static string FinalizerBlock_Name {
            get {
                return ResourceManager.GetString("FinalizerBlock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate proper implementation of the Dispose pattern with a finalizer.
        /// </summary>
        internal static string FinalizerSupressed_Help {
            get {
                return ResourceManager.GetString("FinalizerSupressed_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how you do it.
        /// </summary>
        internal static string FinalizerSupressed_Hint {
            get {
                return ResourceManager.GetString("FinalizerSupressed_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 4 Finalizer: Supressed.
        /// </summary>
        internal static string FinalizerSupressed_Name {
            get {
                return ResourceManager.GetString("FinalizerSupressed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demonstrate improper implementation of the Dispose pattern with a finalizer.
        /// </summary>
        internal static string FinalizerUnsupressed_Help {
            get {
                return ResourceManager.GetString("FinalizerUnsupressed_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not how you do it.
        /// </summary>
        internal static string FinalizerUnsupressed_Hint {
            get {
                return ResourceManager.GetString("FinalizerUnsupressed_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 4 Finalizer: Unsupressed.
        /// </summary>
        internal static string FinalizerUnsupressed_Name {
            get {
                return ResourceManager.GetString("FinalizerUnsupressed_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke GC.Collect() once.  Watch finalizable objects move from the Finalization queue to the fReachable queue..
        /// </summary>
        internal static string GCCollect_Help {
            get {
                return ResourceManager.GetString("GCCollect_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility: GC.Collect().
        /// </summary>
        internal static string GCCollect_Name {
            get {
                return ResourceManager.GetString("GCCollect_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow an object across generations.
        /// </summary>
        internal static string GenHeaps_Help {
            get {
                return ResourceManager.GetString("GenHeaps_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 1: Generational Tracking.
        /// </summary>
        internal static string GenHeaps_Name {
            get {
                return ResourceManager.GetString("GenHeaps_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin up a number of threads that create a dead-lock situation.
        /// </summary>
        internal static string HangOnDeadlock_Help {
            get {
                return ResourceManager.GetString("HangOnDeadlock_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ever get caught in grid-lock traffic.  I hate that!.
        /// </summary>
        internal static string HangOnDeadlock_Hint {
            get {
                return ResourceManager.GetString("HangOnDeadlock_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 3 Hang: Deadlock.
        /// </summary>
        internal static string HangOnDeadlock_Name {
            get {
                return ResourceManager.GetString("HangOnDeadlock_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin up a number of threads that do lots of work.
        /// </summary>
        internal static string HangOnHighCPU_Help {
            get {
                return ResourceManager.GetString("HangOnHighCPU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes it&apos;s tough to get a word in edge-wise.  Who&apos;s the chatter bug?.
        /// </summary>
        internal static string HangOnHighCPU_Hint {
            get {
                return ResourceManager.GetString("HangOnHighCPU_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 3 Hang: High CPU.
        /// </summary>
        internal static string HangOnHighCPU_Name {
            get {
                return ResourceManager.GetString("HangOnHighCPU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin up a number of threads that do little work for a long time..
        /// </summary>
        internal static string HangOnLowCPU_Help {
            get {
                return ResourceManager.GetString("HangOnLowCPU_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may wait a while for this one.  What&apos;s it doing?  Anything?.
        /// </summary>
        internal static string HangOnLowCPU_Hint {
            get {
                return ResourceManager.GetString("HangOnLowCPU_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 3 Hang: Low CPU.
        /// </summary>
        internal static string HangOnLowCPU_Name {
            get {
                return ResourceManager.GetString("HangOnLowCPU_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak blocks of managed data on a separate thread..
        /// </summary>
        internal static string LeakManaged_Help {
            get {
                return ResourceManager.GetString("LeakManaged_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship is going down and all you can do is play music?.
        /// </summary>
        internal static string LeakManaged_Hint {
            get {
                return ResourceManager.GetString("LeakManaged_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 2 Leak: Managed.
        /// </summary>
        internal static string LeakManaged_Name {
            get {
                return ResourceManager.GetString("LeakManaged_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leak blocks of unmanaged data on a separate thread..
        /// </summary>
        internal static string LeakUnmanaged_Help {
            get {
                return ResourceManager.GetString("LeakUnmanaged_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ship is going down and all you can do is play Win32 music?.
        /// </summary>
        internal static string LeakUnmanaged_Hint {
            get {
                return ResourceManager.GetString("LeakUnmanaged_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 2 Leak: Unmanaged.
        /// </summary>
        internal static string LeakUnmanaged_Name {
            get {
                return ResourceManager.GetString("LeakUnmanaged_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raise a managed exception.  What is the exception, which function raised it, and what was the reason?.
        /// </summary>
        internal static string ManagedException_Help {
            get {
                return ResourceManager.GetString("ManagedException_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without exception, this is an exception.
        /// </summary>
        internal static string ManagedException_Hint {
            get {
                return ResourceManager.GetString("ManagedException_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 5: Raise Managed Exception.
        /// </summary>
        internal static string ManagedException_Name {
            get {
                return ResourceManager.GetString("ManagedException_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create some objects for investigation.  Which function created them? What values do they store?.
        /// </summary>
        internal static string ManagedObject_Help {
            get {
                return ResourceManager.GetString("ManagedObject_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 1: Create Managed Objects.
        /// </summary>
        internal static string ManagedObject_Name {
            get {
                return ResourceManager.GetString("ManagedObject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Counters&gt;
        ///	&lt;counter category=&quot;Process&quot; name=&quot;% Processor Time&quot; type=&quot;proctime&quot; /&gt;
        ///	&lt;counter category=&quot;Process&quot; name=&quot;Thread Count&quot; type=&quot;long&quot; /&gt;
        ///	&lt;counter category=&quot;Process&quot; name=&quot;Handle Count&quot; type=&quot;long&quot; /&gt;
        ///	&lt;counter category=&quot;.NET CLR Memory&quot; name=&quot;# of Sink Blocks in use&quot; type=&quot;long&quot; /&gt;
        ///	&lt;counter category=&quot;Process&quot; name=&quot;Private Bytes&quot; type=&quot;long&quot; /&gt;
        ///	&lt;counter category=&quot;.NET CLR Memory&quot; name=&quot;# Bytes in all Heaps&quot; type=&quot;long&quot; /&gt;
        ///	&lt;counter category=&quot;.NET CLR Memory&quot; name=&quot;# Gen 0 Collections&quot; ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PerfCounters {
            get {
                return ResourceManager.GetString("PerfCounters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run a performance analysis for this machine and report the results.
        /// </summary>
        internal static string PerformanceAnalysis_Help {
            get {
                return ResourceManager.GetString("PerformanceAnalysis_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utility: Performance Analysis.
        /// </summary>
        internal static string PerformanceAnalysis_Name {
            get {
                return ResourceManager.GetString("PerformanceAnalysis_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RunningMan {
            get {
                object obj = ResourceManager.GetObject("RunningMan", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spin up 5 managed and 5 thread pool threads and then break.  Which method created these threads?  Which object owns them?.
        /// </summary>
        internal static string SpinUpThreads_Help {
            get {
                return ResourceManager.GetString("SpinUpThreads_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mysterious tapestry will leave you frayed.  Follow the clues to determine the problem..
        /// </summary>
        internal static string SpinUpThreads_Hint {
            get {
                return ResourceManager.GetString("SpinUpThreads_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module 1: Spin up Threads.
        /// </summary>
        internal static string SpinUpThreads_Name {
            get {
                return ResourceManager.GetString("SpinUpThreads_Name", resourceCulture);
            }
        }
    }
}
